// Mocks generated by Mockito 5.4.6 from annotations
// in logistics_management/test/features/shipment/domain/usecases/shipment_lifecycle_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:logistics_management/core/errors/failures.dart' as _i5;
import 'package:logistics_management/features/shipment/domain/models/shipment_model.dart'
    as _i6;
import 'package:logistics_management/features/shipment/domain/repositories/shipment_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ShipmentRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockShipmentRepository extends _i1.Mock
    implements _i3.ShipmentRepository {
  MockShipmentRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>> createShipment({
    required String? clientId,
    required _i6.ShipmentLocation? origin,
    required _i6.ShipmentLocation? destination,
    String? notes,
    double? price = 0.0,
    String? polyline,
    int? distanceMeters = 0,
    int? durationSeconds = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createShipment, [], {
              #clientId: clientId,
              #origin: origin,
              #destination: destination,
              #notes: notes,
              #price: price,
              #polyline: polyline,
              #distanceMeters: distanceMeters,
              #durationSeconds: durationSeconds,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ShipmentModel>(
                    this,
                    Invocation.method(#createShipment, [], {
                      #clientId: clientId,
                      #origin: origin,
                      #destination: destination,
                      #notes: notes,
                      #price: price,
                      #polyline: polyline,
                      #distanceMeters: distanceMeters,
                      #durationSeconds: durationSeconds,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>> getShipment(
    String? shipmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getShipment, [shipmentId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ShipmentModel>(
                    this,
                    Invocation.method(#getShipment, [shipmentId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>);

  @override
  _i4.Stream<_i6.ShipmentModel> streamShipment(String? shipmentId) =>
      (super.noSuchMethod(
            Invocation.method(#streamShipment, [shipmentId]),
            returnValue: _i4.Stream<_i6.ShipmentModel>.empty(),
          )
          as _i4.Stream<_i6.ShipmentModel>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ShipmentModel>>>
  getClientShipments(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#getClientShipments, [clientId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ShipmentModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ShipmentModel>>(
                    this,
                    Invocation.method(#getClientShipments, [clientId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ShipmentModel>>>);

  @override
  _i4.Stream<List<_i6.ShipmentModel>> streamClientShipments(String? clientId) =>
      (super.noSuchMethod(
            Invocation.method(#streamClientShipments, [clientId]),
            returnValue: _i4.Stream<List<_i6.ShipmentModel>>.empty(),
          )
          as _i4.Stream<List<_i6.ShipmentModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ShipmentModel>>>
  getPendingShipments() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingShipments, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ShipmentModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ShipmentModel>>(
                    this,
                    Invocation.method(#getPendingShipments, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ShipmentModel>>>);

  @override
  _i4.Stream<List<_i6.ShipmentModel>> streamPendingShipments() =>
      (super.noSuchMethod(
            Invocation.method(#streamPendingShipments, []),
            returnValue: _i4.Stream<List<_i6.ShipmentModel>>.empty(),
          )
          as _i4.Stream<List<_i6.ShipmentModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ShipmentModel>>>
  getAllShipments() =>
      (super.noSuchMethod(
            Invocation.method(#getAllShipments, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ShipmentModel>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ShipmentModel>>(
                    this,
                    Invocation.method(#getAllShipments, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ShipmentModel>>>);

  @override
  _i4.Stream<List<_i6.ShipmentModel>> streamAllActiveShipments() =>
      (super.noSuchMethod(
            Invocation.method(#streamAllActiveShipments, []),
            returnValue: _i4.Stream<List<_i6.ShipmentModel>>.empty(),
          )
          as _i4.Stream<List<_i6.ShipmentModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>> acceptShipment({
    required String? shipmentId,
    required String? driverId,
    required String? driverName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptShipment, [], {
              #shipmentId: shipmentId,
              #driverId: driverId,
              #driverName: driverName,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ShipmentModel>(
                    this,
                    Invocation.method(#acceptShipment, [], {
                      #shipmentId: shipmentId,
                      #driverId: driverId,
                      #driverName: driverName,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>> startShipment(
    String? shipmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startShipment, [shipmentId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ShipmentModel>(
                    this,
                    Invocation.method(#startShipment, [shipmentId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>> completeShipment(
    String? shipmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#completeShipment, [shipmentId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>.value(
                  _FakeEither_0<_i5.Failure, _i6.ShipmentModel>(
                    this,
                    Invocation.method(#completeShipment, [shipmentId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ShipmentModel>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> cancelShipment(
    String? shipmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cancelShipment, [shipmentId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#cancelShipment, [shipmentId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> updateShipmentRoute({
    required String? shipmentId,
    required String? polyline,
    required int? distanceMeters,
    required int? durationSeconds,
    required DateTime? etaTimestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateShipmentRoute, [], {
              #shipmentId: shipmentId,
              #polyline: polyline,
              #distanceMeters: distanceMeters,
              #durationSeconds: durationSeconds,
              #etaTimestamp: etaTimestamp,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#updateShipmentRoute, [], {
                  #shipmentId: shipmentId,
                  #polyline: polyline,
                  #distanceMeters: distanceMeters,
                  #durationSeconds: durationSeconds,
                  #etaTimestamp: etaTimestamp,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> addLocationPoint({
    required String? shipmentId,
    required _i6.LocationPoint? point,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addLocationPoint, [], {
              #shipmentId: shipmentId,
              #point: point,
            }),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#addLocationPoint, [], {
                  #shipmentId: shipmentId,
                  #point: point,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);

  @override
  _i4.Stream<List<_i6.LocationPoint>> streamLocationHistory(
    String? shipmentId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#streamLocationHistory, [shipmentId]),
            returnValue: _i4.Stream<List<_i6.LocationPoint>>.empty(),
          )
          as _i4.Stream<List<_i6.LocationPoint>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> clearCompletedShipments(
    String? clientId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#clearCompletedShipments, [clientId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#clearCompletedShipments, [clientId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
