// Mocks generated by Mockito 5.4.6 from annotations
// in logistics_management/test/features/auth/domain/usecases/sign_in_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:logistics_management/core/errors/failures.dart' as _i6;
import 'package:logistics_management/features/auth/domain/models/user_model.dart'
    as _i5;
import 'package:logistics_management/features/auth/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.UserModel?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i4.Stream<_i5.UserModel?>.empty(),
          )
          as _i4.Stream<_i5.UserModel?>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel>> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel>>.value(
                  _FakeEither_0<_i6.Failure, _i5.UserModel>(
                    this,
                    Invocation.method(#signIn, [], {
                      #email: email,
                      #password: password,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel>> signUp({
    required String? name,
    required String? email,
    required String? password,
    required String? phone,
    required String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #name: name,
              #email: email,
              #password: password,
              #phone: phone,
              #role: role,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel>>.value(
                  _FakeEither_0<_i6.Failure, _i5.UserModel>(
                    this,
                    Invocation.method(#signUp, [], {
                      #name: name,
                      #email: email,
                      #password: password,
                      #phone: phone,
                      #role: role,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, void>> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<_i2.Either<_i6.Failure, void>>.value(
              _FakeEither_0<_i6.Failure, void>(
                this,
                Invocation.method(#signOut, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, void>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel?>> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel?>>.value(
                  _FakeEither_0<_i6.Failure, _i5.UserModel?>(
                    this,
                    Invocation.method(#getCurrentUser, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel?>>);

  @override
  _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel>> updateProfile({
    required String? userId,
    String? name,
    String? phone,
    String? profileImageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #userId: userId,
              #name: name,
              #phone: phone,
              #profileImageUrl: profileImageUrl,
            }),
            returnValue:
                _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel>>.value(
                  _FakeEither_0<_i6.Failure, _i5.UserModel>(
                    this,
                    Invocation.method(#updateProfile, [], {
                      #userId: userId,
                      #name: name,
                      #phone: phone,
                      #profileImageUrl: profileImageUrl,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i6.Failure, _i5.UserModel>>);
}
